---
title: "Heart"
authors: "Deep Patel, Rodion Stolyar"
date: "4/9/2020"
output: html_document
---

```{r}
library(tidyverse)
library(readr)
library(ROCR)
library(PerformanceAnalytics)
library(e1071)
library(caret)
library(gbm)
library(corrplot)
library(ggcorrplot)
library(MASS)
library(rpart)
library(caTools)
library(naivebayes)
library(class)
library(ISLR)
library(glmnet)
library(Hmisc)
library(funModeling)
library(pROC)
library(randomForest)
library(klaR)
library(scales)
library(cluster)
library(factoextra)
library(DataExplorer)
library(ClustOfVar)
library(GGally)
library(gmodels)
library(C50)


# age: age in years
# sex: (1 = male; 0 = female)
# cp: chest pain type (typical angina, atypical angina, non-angina, or asymptomatic angina)
# trestbps: resting blood pressure (in mm Hg on admission to the hospital)
# chol: serum cholestoral in mg/dl
# fbs: Fasting blood sugar (< 120 mg/dl or > 120 mg/dl) (1 = true; 0 = false)
# restecg: resting electrocardiographic results (normal, ST-T wave abnormality, or left ventricular hypertrophy)
# thalach: Max. heart rate achieved during thalium stress test
# exang: Exercise induced angina (1 = yes; 0 = no)
# oldpeak: ST depression induced by exercise relative to rest
# slope: Slope of peak exercise ST segment (0 = upsloping, 1 = flat, or 2 = downsloping)
# ca: number of major vessels (0-3) colored by flourosopy 4 = NA
# thal: Thalium stress test result 0 = normal or fixed defect, 1 = reversible defect
# thal: 0,1,2,3?
# target: Heart disease status 1 or 0 (0 = heart disease 1 = asymptomatic)


heart <- read.csv("heart.csv")
str(heart)
summary(heart)

```

Methodology

Results and Discussion

```{r}
## Here we are cleaning the data set and modifying the factors

data2 <- heart %>% 
  mutate(sex = if_else(sex == 1, "MALE", "FEMALE"),
         fbs = if_else(fbs == 1, ">120", "<=120"),
         exang = if_else(exang == 1, "YES" ,"NO"),
         cp = if_else(cp == 1, "ATYPICAL ANGINA",
                      if_else(cp == 2, "NON-ANGINAL PAIN", "ASYMPTOMATIC")),
         restecg = if_else(restecg == 0, "NORMAL",
                           if_else(restecg == 1, "ABNORMALITY", "PROBABLE OR DEFINITE")),
         slope = as.factor(slope),
         ca = as.factor(ca),
         thal = as.factor(thal),
         target = if_else(target == 1, "YES", "NO")
         ) %>% 
  mutate_if(is.character, as.factor) %>% 
  dplyr::select(target, sex, fbs, exang, cp, restecg, slope, ca, thal, everything())

summary(data2)

```


```{r}

logit.mode1 <- glm( target ~ . , family = "binomial", data = data2)

summary(logit.mode1)


# when men have the heart attack, men come to ED with pain 
# while women have symptoms that are not nominally associated with heart attack
# moreover gender bias by physician plays a role
# blood sugar >120 is more prone
# old peak is not a sig variable

logit.mode2 <- glm( target ~ sex*cp + .  , family = "binomial", data = data2)

summary(logit.mode2)

# the lower the AIC the better your model, the right direction in lower AIC

#split into test and train

set.seed(12345)
data2_rand <- data2[order(runif(303)), ]

# the 303 number is the number of rows

summary(data2$trestbps)
summary(data2_rand$trestbps)

str(data2)

set.seed(300)
data2_train <- data2_rand[1:240, ]
data2_test  <- data2_rand[241:303, ]

rf <- randomForest(target ~ ., data = data2_train)



rf

data2_pred_rf <- predict(rf, data2_test)
CrossTable(data2_test$target, data2_pred_rf,
           prop.chisq = FALSE, prop.c = FALSE, prop.r = FALSE,
           dnn = c('actual heart disease', 'predicted heart disease'))

accuracy1=(32+22)/(63)
accuracy1
# this model is 85% accurate
# this model accuatately predicted the presence of heart disease 85 percent of the time
# we have 3/63 false negatives


# try decision tree to det imp factor

data2_train$thal = NULL
data2_train$thalach = NULL
data2_train$ca = NULL
data2_train$oldpeak = NULL
data2_train$slope = NULL


# try without thal, thalach, ca, oldpeak, slope
# everyone gets ekg, fasting blood sugar, cholestorol

data2_dt <- C5.0(data2_train[-1], data2_train$target)

#plot will not help but try
plot(data2_dt)

# we can see the most critical factor is checking balance

# display simple facts about the tree
data2_dt

# display detailed information about the tree
summary(data2_dt)

# thal is the principal attribute
# 0 is 




```

